services:
  - type: web
    name: sistema-java
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sistemadb
          property: connectionString

databases:
  - name: sistemadb
    plan: free